server:
  port: 8081

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.90:3306/yunshangdb
    username: root
    password: 12345678

#mybatis:
#  mapper-locations: com/yunshang/shoppingmall/mapper/*.xml
#  type-aliases-package: com.yunshang.shoppingmall.entity