server:
  port: 8091

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.90:3306/yunshangdb
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource   #com.alibaba.druid.pool.DruidDataSource
#    max-wait: 60000
#    max-active: 20
#    minimum-idle: 3
  thymeleaf:
    cache: false

#mybatis:
#  mapper-locations: com/yunshang/shoppingmall/mapper/*.xml
#  type-aliases-package: com.yunshang.shoppingmall.entity